# Generated by Django 2.1 on 2018-08-29 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campsites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=250)),
                ('overview', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=1000)),
                ('images', models.ImageField(blank=True, upload_to='campsite_image')),
                ('rv_sites', models.BooleanField(default=False)),
                ('fire_rings', models.BooleanField(default=False)),
                ('pets_allowed', models.BooleanField(default=False)),
                ('drinking_water', models.BooleanField(default=False)),
                ('toilets', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campsites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=5000)),
                ('rating', models.PositiveIntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pastTents.Campsites')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='campsites',
            name='reviews',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pastTents.Reviews'),
        ),
    ]
