# Generated by Django 2.1 on 2018-08-29 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pastTents', '0002_auto_20180829_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campsites',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campsites', to=settings.AUTH_USER_MODEL),
        ),
    ]
