# Generated by Django 2.1 on 2018-08-29 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pastTents', '0003_auto_20180829_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campsites',
            name='reviews',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pastTents.Reviews'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pastTents.Campsites'),
        ),
    ]
